---
- name: Download bluez
  get_url:
    url: "{{ bluez_artifact_download_url }}"
    dest: "/tmp/{{ bluez_artifact_name }}"
    mode: 0755

- name: Unarchive bluez
  unarchive: src="/tmp/{{ bluez_artifact_name }}" dest="/tmp/"
