---
- name: Download bluez
  get_url:
    url: "{{ bluez_artifact_download_url }}"
    dest: "/tmp/{{ bluez_artifact_name }}"
    mode: 0755

- name: Unarchive bluez
  unarchive: src="/tmp/{{ bluez_artifact_name }}" dest="/tmp/"

- name: Install packages
  package: name={{ item }} state=present
  with_items: "{{ packages }}"

- name: Call configure
  shell: "./configure"
  args:
    chdir: "/tmp/{{ bluez_artifact_dir }}"

- name: Call make
  shell: "make"
  args:
    chdir: "/tmp/{{ bluez_artifact_dir }}"
